
const NAV=[['dashboard','Dashboard','🏠'],['calendar','Kalendarz','📅'],['plan','Plan','🏁'],['log','Wykonanie','✍️'],['coach','Coach Center','🧠'],['garmin','Garmin','⌚'],['backup','Backup','💾']];
const items=(window.PLAN_DATA?.items||[]).map(x=>({...x,date:new Date(x.dateISO+'T12:00:00')}));
const structuredWorkouts=(window.STRUCTURED_WORKOUTS||[]).map(x=>({...x,date:new Date(x.dateISO+'T'+(x.time||'08:00')+':00')}));
const STORAGE_KEY='op_coach_center_logs_v2';
const PREF_KEY='op_coach_center_prefs_v2';
const INTERVALS_KEY='op_coach_center_intervals_v1';
const INTERVALS_ACTIVITIES_KEY='op_coach_center_intervals_activities_v1';
let logs=loadLogs(); let prefs=loadPrefs(); let intervalsData=loadIntervalsData(); let standaloneActivities=loadStandaloneActivities(); let intervalsSyncing=false; let currentView='dashboard';
let calDate=new Date(); if(items.length){calDate=new Date(items[0].dateISO+'T12:00:00')}

function migrateLogs(value){const source=value&&typeof value==='object'&&!Array.isArray(value)?value:{};return Object.fromEntries(Object.entries(source).map(([id,log])=>{if(!log||typeof log!=='object')return [id,{}];const next={...log};if(next.autoSource==='Intervals auto'){next.intervalsId=next.intervalsId||next.autoActivityIds||Object.values(next.parts||{}).map(part=>part.activityId).filter(Boolean).join(',');next.lastSyncedAt=next.lastSyncedAt||next.updated||next.autoMatchedAt||'';}return [id,next]}))}
function migrateStandaloneActivities(value){const source=value&&typeof value==='object'&&!Array.isArray(value)?value:{};return Object.fromEntries(Object.entries(source).map(([id,activity])=>{const record=activity&&typeof activity==='object'?activity:{};return [id,{...record,id:record.id||id,intervalsId:record.intervalsId||record.activityId||record.id||id,lastSyncedAt:record.lastSyncedAt||record.updated||''}]}))}
function loadLogs(){try{return migrateLogs(JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}'))}catch(e){return {}}}
function saveLogs(){localStorage.setItem(STORAGE_KEY,JSON.stringify(logs)); renderAll(); toast('Zapisane ✅')}
function loadPrefs(){try{return JSON.parse(localStorage.getItem(PREF_KEY)||'{}')}catch(e){return {}}}
function savePrefs(){localStorage.setItem(PREF_KEY,JSON.stringify(prefs))}

function loadIntervalsData(){try{return JSON.parse(localStorage.getItem(INTERVALS_KEY)||'null')}catch(e){return null}}
function loadStandaloneActivities(){try{return migrateStandaloneActivities(JSON.parse(localStorage.getItem(INTERVALS_ACTIVITIES_KEY)||'{}'))}catch(e){return {}}}
function saveStandaloneActivities(){localStorage.setItem(INTERVALS_ACTIVITIES_KEY,JSON.stringify(standaloneActivities||{}))}
function saveIntervalsData(data){intervalsData=data;localStorage.setItem(INTERVALS_KEY,JSON.stringify(data||null)); return autoFillLogsFromIntervals(data)}
function intervalsSnapshot(){return intervalsData?.snapshot||intervalsData||null}
function hoursAgo(iso){if(!iso)return '—';const h=(Date.now()-new Date(iso).getTime())/36e5; if(h<1)return Math.max(1,Math.round(h*60))+' min temu'; if(h<48)return Math.round(h)+' h temu'; return Math.round(h/24)+' dni temu'}
async function syncIntervals(force=false){
  if(intervalsSyncing)return; intervalsSyncing=true; updateIntervalsButtons(true);
  try{
    const res=await fetch('/.netlify/functions/intervals-sync'+(force?'?force=1':''),{method:force?'POST':'GET'});
    const data=await res.json();
    if(!res.ok||!data.ok)throw new Error(data.error||'Błąd synchronizacji Intervals.icu');
    const autoCount = saveIntervalsData(data.snapshot?data:{snapshot:data});
    toast((force?'Intervals: zsynchronizowano live ✅':'Intervals: dane odświeżone ✅') + (autoCount ? ` • uzupełniono ${autoCount} treningów` : ''));
    renderAll();
  }catch(err){toast('Intervals: '+err.message); console.error(err)}
  finally{intervalsSyncing=false; updateIntervalsButtons(false)}
}
function updateIntervalsButtons(busy){document.querySelectorAll('[data-intervals-sync]').forEach(b=>{b.disabled=busy;b.textContent=busy?'Synchronizuję…':'Synchronizuj teraz'})}
function intervalsPanel(){
  const snap=intervalsSnapshot();
  if(!snap)return `<div class="section-title"><div><h3>Intervals.icu live sync</h3><p>Połączone przez Netlify Functions. Dane będą pobierane 3× dziennie i ręcznie na klik.</p></div><button class="btn primary" data-intervals-sync onclick="syncIntervals(true)">Synchronizuj teraz</button></div><div class="card"><p style="color:var(--muted);line-height:1.6">Brak pobranego snapshotu. Po wdrożeniu na Netlify ustaw zmienną <code>INTERVALS_API_KEY</code>, a potem kliknij synchronizację.</p></div>`;
  const t=snap.totals||{}, l7=snap.last7||{}, l30=snap.last30||{}, w=snap.wellness||{};
  const standalone=Object.values(standaloneActivities).sort((a,b)=>String(b.startDateLocal||b.date).localeCompare(String(a.startDateLocal||a.date))).slice(0,5);
  return `<div class="section-title"><div><h3>Intervals.icu live sync</h3><p>Ostatnia synchronizacja: ${esc(hoursAgo(snap.syncedAt))} • ostatnia aktywność: ${esc(t.lastActivityDate||'—')}</p></div><button class="btn primary" data-intervals-sync onclick="syncIntervals(true)">Synchronizuj teraz</button></div>
  <div class="grid cols-4">
    ${metric('Aktywności 7 dni',l7.count||0,`${(l7.hours||0).toFixed?l7.hours.toFixed(1):l7.hours||0} h • ${l7.km||0} km`)}
    ${metric('Load 7 dni',l7.load||0,'z Intervals.icu')}
    ${metric('Aktywności 30 dni',l30.count||0,`${l30.hours||0} h • ${l30.km||0} km`)}
    ${metric('Sen / HRV',`${w.avgSleep||'—'} / ${w.avgHRV||'—'}`,'średnia wellness 14 dni')}
  </div>${standalone.length?`<div class="card"><h3 style="margin-top:0">Aktywności poza planem / do przypisania</h3><table class="table"><thead><tr><th>Data</th><th>Typ</th><th>Nazwa</th><th>Status</th></tr></thead><tbody>${standalone.map(a=>`<tr><td>${esc(a.date||'')}</td><td>${esc(a.sport||'')}</td><td>${esc(a.name||'')}</td><td>${esc(a.status||'Poza planem')}</td></tr>`).join('')}</tbody></table></div>`:''}`
}
function intervalsCoachPanel(){
  const snap=intervalsSnapshot(); if(!snap)return '<div class="card"><h3>Intervals.icu</h3><p style="color:var(--muted)">Brak danych live. Zsynchronizuj po wdrożeniu na Netlify.</p></div>';
  const acts=snap.activities||[];
  return `<div class="card"><h3 style="margin-top:0">Ostatnie aktywności z Intervals.icu</h3>${acts.length?`<table class="table"><thead><tr><th>Data</th><th>Typ</th><th>Nazwa</th><th>Km</th><th>h</th><th>Load</th></tr></thead><tbody>${acts.slice(0,8).map(a=>`<tr><td>${esc(a.date||'')}</td><td>${esc(a.type||'')}</td><td>${esc(a.name||'')}</td><td>${esc(a.km||0)}</td><td>${esc(a.hours||0)}</td><td>${esc(a.load||0)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Brak aktywności w pobranym zakresie.</div>'}</div>`;
}

function extractIntervalsActivities(data){
  const snap = data?.snapshot || data || intervalsSnapshot() || {};
  const arr = snap.activities || snap.recentActivities || snap.activity || [];
  return Array.isArray(arr) ? arr : [];
}
function autoFillLogsFromIntervals(data){
  try{
    const snap=data?.snapshot||data||{};
    const engine=window.IntervalsAutofillEngine;
    if(!engine)throw new Error('Brak silnika IntervalsAutofillEngine');
    const result=engine.sync({items,structuredWorkouts,activities:extractIntervalsActivities(data),events:Array.isArray(snap.events)?snap.events:[],logs,standalone:standaloneActivities,syncedAt:snap.syncedAt||new Date().toISOString()});
    logs=result.logs; standaloneActivities=result.standalone;
    localStorage.setItem(STORAGE_KEY,JSON.stringify(logs)); saveStandaloneActivities();
    localStorage.setItem('op_last_autofill_count',String(result.matched.length));
    return result.matched.length;
  }catch(e){console.error('Auto-fill Intervals error', e); return 0;}
}

function $(id){return document.getElementById(id)}
function esc(s){return String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function fmtDate(d){return new Intl.DateTimeFormat('pl-PL',{day:'2-digit',month:'short',year:'numeric'}).format(d)}
function iso(d){return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
function monthName(d){return new Intl.DateTimeFormat('pl-PL',{month:'long',year:'numeric'}).format(d)}
function todayIso(){return iso(new Date())}
function isRest(it){return window.IntervalsAutofillEngine?.isRest(it)??/(^|[\s/+-])(WOLNE|REST|OFF)([\s/+-]|$)/i.test(it.discipline||'')}
function num(v){let n=parseFloat(String(v||'').replace(',','.'));return isFinite(n)?n:0}
function getLog(id){return logs[id]||{}}
function merged(it){return {...it,...getLog(it.id)}}
function findTodayPlan(){const t=todayIso(); return items.find(x=>x.dateISO===t)||nextWorkout()}
function nextWorkout(){const now=new Date(); return items.find(x=>x.date>=new Date(now.toDateString()))||items[items.length-1]}
function loggedItems(days=9999){const cutoff=new Date(); cutoff.setDate(cutoff.getDate()-days+1); return items.map(merged).filter(x=>logs[x.id] && x.date>=cutoff)}
function avg(arr,field){const vals=arr.map(x=>num(x[field])).filter(x=>x>0); return vals.length? vals.reduce((a,b)=>a+b,0)/vals.length : 0}
function countCond(arr,fn){return arr.filter(fn).length}
function readiness(){
  const l7=loggedItems(7), l14=loggedItems(14);
  const rpe=avg(l7,'rpe'), pain=avg(l7,'pain'), sleep=avg(l7,'sleep'), mental=avg(l7,'mental');
  const pain3=countCond(l14,x=>num(x.pain)>=3), pain5=countCond(l14,x=>num(x.pain)>=5);
  let score=88;
  if(rpe>0) score-=Math.max(0,(rpe-4.5)*7);
  if(pain>0) score-=pain*6;
  if(sleep>0) score-=Math.max(0,(6.8-sleep)*8);
  if(mental>0) score-=Math.max(0,(6-mental)*5);
  score-=pain3*3+pain5*8;
  score=Math.max(15,Math.min(100,Math.round(score)));
  if(!l7.length) return {score:null,label:'BRAK DANYCH',class:'warn',comment:'Uzupełnij kilka treningów, żeby panel zaczął liczyć realną gotowość.',rpe,pain,sleep,mental,pain3,pain5};
  let label='ZIELONY'; let cls='good'; let comment='Petarda: regeneracja wygląda dobrze. Realizuj plan, ale bez dokładania.';
  if(score<75){label='ŻÓŁTY';cls='warn';comment='Kontynuuj, ale skróć akcent lub pilnuj RPE. Zero dokładania.'}
  if(score<60){label='POMARAŃCZOWY';cls='warn';comment='Zamień mocny trening na easy / basen / Z1-Z2. Priorytet: sen i tkanki.'}
  if(score<45){label='CZERWONY';cls='bad';comment='Stop dla mocnych bodźców. Wolne albo regeneracja. Jeśli ból rośnie — fizjo/lekarz.'}
  return {score,label,class:cls,comment,rpe,pain,sleep,mental,pain3,pain5};
}
function planBFor(it,rd=readiness()){
  if(!it) return 'Brak treningu w planie.';
  if(rd.score===null) return 'Realizuj plan, ale wpisz RPE/ból/sen po treningu.';
  const disc=(it.discipline||'').toLowerCase(), desc=it.description||'';
  if(rd.score>=75) return 'Realizuj plan. Nie dokładaj ekstra.';
  if(/start|test/i.test(desc+' '+disc)) return rd.score<60?'Przenieś test albo zrób tylko rozgrzewkę + easy.':'Zrób test kontrolnie, bez walki o rekord.';
  if(/long|długi|bieg/i.test(disc+' '+desc) && /bieg/i.test(disc+' '+desc)) return rd.score<60?'Skróć do 50-65% dystansu, tylko easy.':'Skróć o 20-30%, bez bloków race pace.';
  if(/tacx|rower|bike/i.test(disc+' '+desc)) return rd.score<60?'45-60 min Z1/Z2, bez T2.':'Zostaw Z2, usuń sweet spot / race pace / T2.';
  if(/basen|pływ|open water/i.test(disc+' '+desc)) return rd.score<60?'Luźne 20-30 min technika albo wolne.':'Płyń technicznie, bez mocnych serii.';
  return rd.score<60?'Zamień na spacer, mobilność lub wolne.':'Skróć o 20-30% i trzymaj RPE nisko.';
}
function adaptiveHistoryInput(){return items.map(workout=>({workout,execution:logs[workout.id]||{},manual:logs[workout.id]||{}}))}
function adaptiveWorkoutForSelection(selection){if(selection.item)return selection.item;const record=selection.record||{};return {id:`activity:${selection.id}`,dateISO:record.date||String(record.activityStart||'').slice(0,10),sport:record.sport,discipline:record.name||record.activityName||'Aktywność poza planem',workoutType:'UNPLANNED',intensity:'POZA PLANEM',required:false,optional:false}}
function adaptiveEvaluationForSelection(selection){const engine=window.AdaptiveCoachEngine;if(!engine)return null;const workout=adaptiveWorkoutForSelection(selection);return engine.evaluate({workout,execution:selection.record||{},manual:selection.record||{},plan:items,history:adaptiveHistoryInput()})}
function adaptiveEntries(){const planned=Object.entries(logs).map(([id,record])=>{const item=items.find(workout=>workout.id===id);return item?{kind:'plan',id,record,item,date:item.dateISO}:null}).filter(Boolean);const outside=Object.values(standaloneActivities).map(record=>({kind:'activity',id:record.id,record,item:null,date:record.date||String(record.activityStart||'').slice(0,10)}));return [...planned,...outside].filter(entry=>entry.record.autoSource||entry.record.status||entry.record.updated).sort((a,b)=>String(b.date).localeCompare(String(a.date))||String(b.id).localeCompare(String(a.id)))}
function latestAdaptiveEvaluation(){const entry=adaptiveEntries()[0];if(entry){const result=adaptiveEvaluationForSelection(entry);return {entry,result}}const next=items.find(item=>item.dateISO>=todayIso()&&window.AdaptiveCoachEngine?.isRequired(item));const result=window.AdaptiveCoachEngine?.evaluate({workout:{dateISO:todayIso()},execution:{},manual:{},nextWorkout:next,plan:items,history:[]});return {entry:null,result}}
function adaptiveClass(status){return status==='green'?'green':status==='yellow'?'amber':'red'}
function confidenceLabel(result){if(result?.confidence==='full')return 'Ocena pełna';if(result?.confidence==='provisional')return 'Ocena wstępna';return 'Za mało danych'}
function adaptiveRecommendationHtml(){const {result}=latestAdaptiveEvaluation();if(!result)return '<div class="empty">Silnik rekomendacji nie został załadowany.</div>';const insufficient=result.confidence==='insufficient';const color=insufficient?'amber':adaptiveClass(result.status);const headline=insufficient?'ZA MAŁO DANYCH — ocena wstępna':result.headline;const variant=insufficient?'ocena wstępna':result.recommendedVariant;const action=insufficient?'Po synchronizacji wykonanego treningu uzupełnij RPE, ból i sen. Do tego czasu nie zwiększaj obciążenia.':result.recommendedAction;const missing=result.missingData?.length?`<p class="coach-missing">Uzupełnij: ${result.missingData.map(field=>({rpe:'RPE',pain:'ból',sleep:'sen'}[field]||field)).join(', ')}.</p>`:'';return `<div class="card coach-recommendation ${color}"><div class="coach-verdict"><span class="coach-dot"></span><div><span class="pill ${color}">${esc(headline)}</span><h3>${esc(result.nextWorkoutName||'Najbliższy obowiązkowy trening')}</h3></div></div><p class="coach-action"><b>${esc(variant)}</b> — ${esc(action)}</p><ul class="coach-reasons">${result.reasons.slice(0,3).map(reason=>`<li>${esc(reason)}</li>`).join('')}</ul>${missing}<p class="coach-disclaimer">Rekomendacja nie zmienia automatycznie planu ani Intervals.icu.</p></div>`}
function adaptiveAssessmentHtml(selection){const record=selection.record||{};const hasInput=Object.values(record).some(value=>value!==null&&value!==undefined&&value!=='');if(!hasInput)return '';const result=adaptiveEvaluationForSelection(selection);if(!result)return '';const used=result.usedInputs||{};const fields=[['Wykonanie planu',used.completionPercentage==null?'brak danych':used.completionPercentage+'%'],['Zgodność intensywności',result.status==='green'?'zgodna':'wymaga uwagi'],['Ból',used.pain==null?'brak danych':used.pain+'/10'],['RPE',used.rpe==null?'brak danych':used.rpe],['Sen',used.sleep==null?'brak danych':used.sleep+' h'],['Load',used.load==null?'brak danych':used.load]];const visible=fields.filter(([,value])=>value!=='');return `<div class="section-title"><div><h3>Ocena wykonania</h3><p>${confidenceLabel(result)} • ${result.scope==='whole-activity'?'ocena całej aktywności — brak danych okrążeń/kroków':'uwzględniono dostępne okrążenia'}</p></div><span class="pill ${adaptiveClass(result.status)}">${esc(result.headline)}</span></div><div class="card assessment-card"><div class="detail-grid">${visible.map(([label,value])=>`<div class="detail-item"><b>${esc(label)}</b><p>${esc(value)}</p></div>`).join('')}</div><h4>Wynik i użyte dane</h4><ul class="coach-reasons">${result.reasons.slice(0,3).map(reason=>`<li>${esc(reason)}</li>`).join('')}</ul>${result.missingData.length?`<p class="coach-missing">Ocena wstępna. Brakuje: ${result.missingData.map(field=>({rpe:'RPE',pain:'ból',sleep:'sen'}[field]||field)).join(', ')}.</p>`:''}</div>`}
function adaptiveGatesHtml(){const gates=window.AdaptiveCoachEngine?.gateStatuses({plan:items,logs,nowDate:todayIso()})||[];return `<div class="section-title"><div><h3>Bramki celu 3:30</h3><p>Ukończenie dystansu samo nie zalicza bramki</p></div></div><div class="grid cols-4 gate-grid">${gates.map(gate=>`<div class="card slim gate-card"><b>${esc(gate.label)}</b><span class="pill ${gate.status==='zaliczona'?'green':gate.status==='niezaliczona'?'red':'amber'}">${esc(gate.status)}</span>${gate.reason?`<p>${esc(gate.reason)}</p>`:''}</div>`).join('')}</div>`}
function adaptiveHistoryHtml(){const rows=adaptiveEntries().slice(0,5).map(entry=>{const result=adaptiveEvaluationForSelection(entry);return `<tr><td>${esc(entry.date)}</td><td>${esc(entry.item?.discipline||entry.record.name||entry.record.activityName||'Aktywność')}</td><td><span class="pill ${adaptiveClass(result.status)}">${esc(result.headline.split(' — ')[0])}</span></td><td>${esc(result.reasons[0]||'—')}</td></tr>`});return `<div class="section-title"><div><h3>Ostatnie oceny</h3><p>Pięć ostatnich wykonanych treningów</p></div></div><div class="card adaptive-history">${rows.length?`<table class="table"><thead><tr><th>Data</th><th>Trening</th><th>Status</th><th>Główny powód</th></tr></thead><tbody>${rows.join('')}</tbody></table>`:'<div class="empty">Brak wykonanych treningów do oceny.</div>'}</div>`}
function updateNav(){const navHtml=NAV.map(([id,label,ico])=>`<button class="${id===currentView?'active':''}" data-view="${id}"><span>${ico}</span><span>${label}</span></button>`).join(''); $('sideNav').innerHTML=navHtml; $('mobileNav').innerHTML=navHtml; document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));}
function showView(id){currentView=id; document.querySelectorAll('.view').forEach(v=>v.classList.remove('active')); $(`view-${id}`).classList.add('active'); updateNav(); const titles={dashboard:['Dashboard','Centrum dowodzenia treningiem'],calendar:['Kalendarz','Każda jednostka treningowa z opisem'],plan:['Plan treningowy','Filtruj, szukaj i otwieraj szczegóły'],log:['Szczegóły wykonania','Dane obiektywne z Intervals.icu oraz Twoja opcjonalna ocena'],coach:['Coach Center','Readiness, Plan B, paliwo, buty i predykcja'],garmin:['Garmin sync','Eksport do Intervals.icu i kalendarza Garmin'],backup:['Backup / eksport','Przenieś dane między komputerem, telefonem i tabletem']}; $('pageTitle').textContent=titles[id][0]; $('pageSub').textContent=titles[id][1]; renderView(id);}
function renderAll(){updateNav(); ['dashboard','calendar','plan','log','coach','garmin','backup'].forEach(renderView); const rd=readiness(); $('sideScore').textContent=rd.score??'—'; $('sideRing').style.setProperty('--p', (rd.score??0)+'%'); $('sideComment').textContent=rd.comment;}
function renderView(id){const fn={dashboard:renderDashboard,calendar:renderCalendar,plan:renderPlan,log:renderLog,coach:renderCoach,garmin:renderGarmin,backup:renderBackup}[id]; if(fn) fn();}
function metric(label,value,hint,cls=''){return `<div class="card metric ${cls}"><div class="label">${label}</div><div class="value">${value}</div><div class="hint">${hint}</div></div>`}
function renderDashboard(){const rd=readiness(); const today=findTodayPlan(); const next=nextWorkout(); const scoredItems=items.filter(item=>item.required!==false&&!item.optional&&!isRest(item)); const done=scoredItems.filter(item=>{const log=logs[item.id];return log&&log.status!=='Częściowo'}).length; const total=scoredItems.length; const compl=total?Math.round(done/total*100):0;
  $('view-dashboard').innerHTML=`
  <div class="grid cols-4">
    ${metric('Readiness', rd.score===null?'—':rd.score+'/100', rd.label||'uzupełnij dane', rd.class)}
    ${metric('Wpisy', done, `z ${total} jednostek (${compl}%)`)}
    ${metric('Śr. RPE 7 dni', rd.rpe?rd.rpe.toFixed(1):'—', 'odczuwalna ciężkość')}
    ${metric('Śr. sen 7 dni', rd.sleep?rd.sleep.toFixed(1)+' h':'—', 'regeneracja')}
  </div>
  <div class="section-title"><div><h3>Rekomendacja trenera</h3><p>Deterministyczna ocena wykonania i następnego treningu</p></div></div>
  ${adaptiveRecommendationHtml()}
  ${adaptiveGatesHtml()}
  ${intervalsPanel()}
  <div class="section-title"><div><h3>Najbliższy trening</h3><p>Plan + automatyczny Plan B wg aktualnej gotowości</p></div><span class="pill ${rd.class||''}">${rd.label||'BRAK DANYCH'}</span></div>
  <div class="grid cols-2"><div class="card">${workoutFull(today,true)}</div><div class="card"><h3 style="margin-top:0">Coach comment</h3><p style="color:var(--muted);line-height:1.55">${esc(rd.comment)}</p><div class="detail-item"><b>Plan B</b><p>${esc(planBFor(today,rd))}</p></div></div></div>
  <div class="section-title"><div><h3>Ten tydzień</h3><p>Podgląd jednostek w najbliższych 7 dniach</p></div></div>
  <div class="list">${items.filter(x=>{let d=new Date();let e=new Date();e.setDate(e.getDate()+7);return x.date>=new Date(d.toDateString())&&x.date<=e}).map(workoutRow).join('')||'<div class="empty">Brak nadchodzących treningów.</div>'}</div>
  ${adaptiveHistoryHtml()}`;
}
function workoutFull(it,button=false){if(!it)return '<div class="empty">Brak jednostki.</div>'; const l=getLog(it.id); return `<div class="tagline"><span class="pill green">${esc(it.Phase)}</span><span class="pill">${esc(it.intensity)}</span><span class="pill">${esc(it.week)}</span>${it.alternativeGroup?'<span class="pill warn">wykonaj tylko jedną opcję</span>':''}</div><h3 style="margin:12px 0 4px">${esc(it.discipline)}</h3><p style="color:var(--muted);margin:0 0 12px">${fmtDate(it.date)} • ${esc(it['Dzień']||'')}</p><p style="line-height:1.55">${esc(it.description)}</p><div class="detail-grid"><div class="detail-item"><b>Cel</b><p>${esc(it.goal)}</p></div>${it.paceDisplay?`<div class="detail-item"><b>Tempo i RPE — wszystkie bloki</b><p>${esc(it.paceDisplay)}</p></div>`:''}<div class="detail-item"><b>Żywienie</b><p>${esc(it.breakfast)} ${esc(it.lunch)} ${esc(it.dinner)}</p></div>${it.modification?`<div class="detail-item"><b>Plan B / warunki</b><p>${esc(it.modification)}</p></div>`:''}</div>${l.rpe?`<div class="tagline"><span class="pill green">RPE ${l.rpe}</span><span class="pill">ból ${l.pain||0}</span><span class="pill">sen ${l.sleep||'—'}h</span></div>`:''}${button?`<div style="margin-top:14px"><button class="btn primary" onclick="prefillLog('${it.id}')">Dodaj RPE / notatkę</button> <button class="btn" onclick="openWorkout('${it.id}')">Szczegóły</button></div>`:''}`}
function workoutRow(it){const log=logs[it.id]; const status=log?.status==='Częściowo'?'<span class="pill warn">częściowo</span>':log?.status==='Niewymagana / wybrano inną opcję'?'<span class="pill">wybrano inną opcję</span>':log?'<span class="pill green">uzupełnione</span>':''; const sharedBlock=it.parentId&&items.some(other=>other.id!==it.id&&other.parentId===it.parentId); return `<div class="workout-row" onclick="openWorkout('${it.id}')"><div class="datebox">${fmtDate(it.date)}<small>${esc(it['Dzień']||'')}</small></div><div><h4>${esc(it.discipline)}</h4>${it.paceSummary?`<p><b>Tempo:</b> ${esc(it.paceSummary)}</p>`:''}<p>${esc(it.description)}</p><div class="tagline"><span class="pill">${esc(it.intensity)}</span><span class="pill">${esc(it.week)}</span>${sharedBlock?'<span class="pill">wspólny blok</span>':''}${it.alternativeGroup?'<span class="pill warn">wykonaj tylko jedną opcję</span>':''}${status}</div></div><button class="btn" onclick="event.stopPropagation();prefillLog('${it.id}')">Dodaj RPE / notatkę</button></div>`}
function renderCalendar(){const y=calDate.getFullYear(), m=calDate.getMonth(); const first=new Date(y,m,1); const start=new Date(first); const offset=(first.getDay()+6)%7; start.setDate(first.getDate()-offset); const days=[]; for(let i=0;i<42;i++){let d=new Date(start);d.setDate(start.getDate()+i);days.push(d)}
 const monthItems=items.filter(x=>x.date.getFullYear()===y&&x.date.getMonth()===m);
 $('view-calendar').innerHTML=`<div class="card"><div class="calendar-head"><button class="btn" id="prevMonth">←</button><h3>${monthName(calDate)}</h3><button class="btn" id="nextMonth">→</button></div><div class="toolbar"><button class="btn" id="todayMonth">Dzisiaj</button><select id="monthJump">${[...new Set(items.map(x=>x.monthKey))].map(k=>{let [yy,mm]=k.split('-').map(Number);return `<option value="${k}" ${yy===y&&mm-1===m?'selected':''}>${monthName(new Date(yy,mm-1,1))}</option>`}).join('')}</select></div><div class="calendar-grid">${['Pon','Wt','Śr','Czw','Pt','Sob','Nd'].map(d=>`<div class="dow">${d}</div>`).join('')}${days.map(d=>calendarDay(d,m)).join('')}</div></div><div class="section-title"><div><h3>Lista miesiąca</h3><p>${monthItems.length} jednostek</p></div></div><div class="list">${monthItems.map(workoutRow).join('')}</div>`;
 $('prevMonth').onclick=()=>{calDate.setMonth(calDate.getMonth()-1);renderCalendar()}; $('nextMonth').onclick=()=>{calDate.setMonth(calDate.getMonth()+1);renderCalendar()}; $('todayMonth').onclick=()=>{calDate=new Date();renderCalendar()}; $('monthJump').onchange=e=>{const [yy,mm]=e.target.value.split('-').map(Number);calDate=new Date(yy,mm-1,1);renderCalendar()};}
function calendarDay(d,curM){const ds=iso(d); const dayItems=items.filter(x=>x.dateISO===ds); const external=Object.values(standaloneActivities).filter(x=>x.date===ds); const today=ds===todayIso(); const allCount=dayItems.length+external.length; return `<div class="day ${d.getMonth()!==curM?'off':''} ${today?'today':''}"><div class="day-num"><span>${d.getDate()}</span>${logsForDate(ds).length||external.length?'<span class="pill green">✓</span>':''}</div>${dayItems.slice(0,3).map(x=>`<div class="event ${eventClass(x)}" onclick="openWorkout('${x.id}')"><div class="e-title">${esc(x.discipline)}</div><div class="e-meta">${esc(x.intensity)}${x.paceSummary?` • ${esc(x.paceSummary)}`:''}${x.alternativeGroup?' • wybierz jedną opcję':''}</div></div>`).join('')}${external.slice(0,Math.max(0,3-dayItems.length)).map(x=>`<div class="event" onclick="prefillStandalone('${esc(x.id)}')"><div class="e-title">${esc(x.name)}</div><div class="e-meta">${esc(x.status)}</div></div>`).join('')}${allCount>3?`<div class="pill">+${allCount-3}</div>`:''}</div>`}
function eventClass(x){let s=((x.intensity||'')+' '+(x.discipline||'')).toUpperCase(); if(/LONG/.test(s))return 'LONG'; if(/START|TEST|MOCNY|INTERWA/.test(s))return 'MOCNY'; if(/BASEN|OPEN/.test(s))return 'BASEN'; if(/TACX|ROWER/.test(s))return 'TACX'; if(/WOLNE|REGENER/.test(s))return 'REGENERACJA'; return ''}
function logsForDate(ds){return Object.entries(logs).filter(([id])=>items.find(x=>x.id===id)?.dateISO===ds)}
function renderPlan(){const phases=[...new Set(items.map(x=>x.Phase))]; const intens=[...new Set(items.map(x=>x.intensity).filter(Boolean))]; $('view-plan').innerHTML=`<div class="toolbar"><div class="search"><input class="input" id="planSearch" placeholder="Szukaj: rytmy, long, Tacx, CSS..." /></div><select id="phaseFilter"><option value="">Wszystkie fazy</option>${phases.map(p=>`<option>${esc(p)}</option>`).join('')}</select><select id="intFilter"><option value="">Każda intensywność</option>${intens.map(p=>`<option>${esc(p)}</option>`).join('')}</select></div><div class="list" id="planList"></div>`; const update=()=>{let q=$('planSearch').value.toLowerCase(), ph=$('phaseFilter').value, itf=$('intFilter').value; let arr=items.filter(x=>(!ph||x.Phase===ph)&&(!itf||x.intensity===itf)&&(!q||JSON.stringify(x).toLowerCase().includes(q))); $('planList').innerHTML=arr.slice(0,300).map(workoutRow).join('')+(arr.length>300?`<div class="empty">Pokazuję 300 z ${arr.length}. Zawęź wyszukiwanie.</div>`:'')||'<div class="empty">Brak wyników.</div>'}; ['planSearch','phaseFilter','intFilter'].forEach(id=>setTimeout(()=>$(id).oninput=update)); update();}
const MANUAL_LOG_FIELDS={logRpe:'rpe',logPain:'pain',logSleep:'sleep',logMental:'mental',logShoes:'shoes',logFuel:'fuel',logNotes:'notes'};
function executionSelection(value){if(String(value||'').startsWith('activity:')){const id=String(value).slice(9);return {kind:'activity',id,record:standaloneActivities[id]||{},item:null}}const id=value||'';return {kind:'plan',id,record:logs[id]||{},item:items.find(item=>item.id===id)}}
function objectiveInput(label,value,unit=''){const shown=value!==null&&value!==undefined&&value!==''?`${value}${unit}`:'';return `<div><label>${esc(label)}</label><input class="input objective" readonly value="${esc(shown)}"></div>`}
function formatExecutionStart(record){return String(record.activityStart||record.startDateLocal||record.startDate||record.activityDate||record.date||'').replace('T',' ').slice(0,16)}
function executionParts(record){const parts=Object.values(record.parts||{});if(!parts.length)return '';return `<div class="full"><h4>Części jednostki</h4><div style="overflow:auto"><table class="table"><thead><tr><th>Nazwa</th><th>Start</th><th>Czas</th><th>Dystans</th><th>HR</th><th>Moc</th><th>Intervals ID</th></tr></thead><tbody>${parts.map(part=>`<tr><td>${esc(part.activityName||'Aktywność')}</td><td>${esc(formatExecutionStart(part)||'—')}</td><td>${esc(part.time||0)} min</td><td>${esc(part.km||0)} km</td><td>${esc(part.avgHr||'—')} / ${esc(part.maxHr||'—')}</td><td>${esc(part.avgWatts||'—')} / ${esc(part.normalizedWatts||'—')} W</td><td>${esc(part.intervalsId||part.activityId||'—')}</td></tr>`).join('')}</tbody></table></div></div>`}
function objectiveExecutionHtml(selection){const record=selection.record||{};const name=record.activityName||record.name||'';const intervalsId=record.intervalsId||record.autoActivityIds||record.activityId||'';return `<div class="form-grid objective-grid">${objectiveInput('Status',record.status)}${objectiveInput('Nazwa aktywności',name)}${objectiveInput('Data i godzina',formatExecutionStart(record))}${objectiveInput('Czas',record.time,' min')}${objectiveInput('Dystans',record.km,' km')}${objectiveInput('Tempo',record.pace,' min/km')}${objectiveInput('Prędkość',record.speed,' km/h')}${objectiveInput('Tętno śr. / max',record.avgHr||record.maxHr?`${record.avgHr||'—'} / ${record.maxHr||'—'}`:'')}${objectiveInput('Moc śr. / norm.',record.avgWatts||record.normalizedWatts?`${record.avgWatts||'—'} / ${record.normalizedWatts||'—'}`:'',' W')}${objectiveInput('Kadencja',record.cadence)}${objectiveInput('Przewyższenie',record.elevation,' m')}${objectiveInput('Kalorie',record.calories,' kcal')}${objectiveInput('Load',record.load)}${objectiveInput('Wykonanie planu',record.done,'%')}${objectiveInput('Intervals ID',intervalsId)}${objectiveInput('Źródło',record.autoSource)}${objectiveInput('Ostatnia synchronizacja',formatExecutionStart({activityStart:record.lastSyncedAt}))}${executionParts(record)}</div>`}
function renderLog(){const selected=$('logWorkout')?.value;const plannedOptions=items.map(x=>`<option value="${x.id}">${x.dateISO} • ${x.discipline} • ${x.week}</option>`).join('');const activityOptions=Object.values(standaloneActivities).sort((a,b)=>String(b.activityStart||b.date).localeCompare(String(a.activityStart||a.date))).map(x=>`<option value="activity:${esc(x.id)}">${esc(x.date||'')} • ${esc(x.name||'Aktywność')} • ${esc(x.status||'Poza planem')}</option>`).join('');$('view-log').innerHTML=`<div class="card"><h3 style="margin-top:0">Szczegóły wykonania</h3><p style="color:var(--muted)">Dane wykonania synchronizują się automatycznie z Intervals.icu</p><div class="form-grid"><div class="full"><label>Trening lub aktywność</label><select id="logWorkout"><optgroup label="Plan treningowy">${plannedOptions}</optgroup>${activityOptions?`<optgroup label="Poza planem / do przypisania">${activityOptions}</optgroup>`:''}</select></div><div class="full" id="objectiveExecution"></div></div><div id="executionAssessment"></div><details class="manual-details"><summary>Moja ocena i notatki</summary><div class="form-grid" style="margin-top:14px"><div><label>RPE 1-10</label><input id="logRpe" class="input" type="number" min="1" max="10" step="1"></div><div><label>Ból 0-10</label><input id="logPain" class="input" type="number" min="0" max="10" step="1"></div><div><label>Sen (h)</label><input id="logSleep" class="input" type="number" min="0" step="0.1"></div><div><label>Mental 1-10</label><input id="logMental" class="input" type="number" min="1" max="10" step="1"></div><div class="wide"><label>Buty / sprzęt</label><input id="logShoes" class="input" placeholder="np. Metaspeed / Tacx / pianka"></div><div class="wide"><label>Paliwo / żele</label><input id="logFuel" class="input" placeholder="np. 3 żele, 750 ml, sód"></div><div class="full"><label>Prywatna notatka użytkownika</label><textarea id="logNotes" placeholder="Jak weszło, co bolało, co zadziałało, co poprawić?"></textarea></div></div><div style="margin-top:16px;display:flex;gap:10px;flex-wrap:wrap"><button class="btn primary" id="saveLog">Zapisz RPE / notatkę</button><button class="btn warn" id="deleteLog">Wyczyść moją ocenę</button></div></details></div><div class="section-title"><div><h3>Historia wykonanych aktywności</h3><p>Plan, aktywności poza planem i rekordy wymagające przypisania</p></div></div><div class="list" id="recentLogs"></div>`;$('logWorkout').onchange=loadLogForm;$('saveLog').onclick=saveLogForm;$('deleteLog').onclick=deleteLogForm;const next=findTodayPlan();const values=[...$('logWorkout').options].map(option=>option.value);$('logWorkout').value=values.includes(selected)?selected:(next?.id||items[0]?.id);loadLogForm();renderRecentLogs();}
function previewAdaptiveAssessment(){const selection=executionSelection($('logWorkout').value);const manual=Object.fromEntries(Object.entries(MANUAL_LOG_FIELDS).map(([el,key])=>[key,$(el)?.value||'']));$('executionAssessment').innerHTML=adaptiveAssessmentHtml({...selection,record:{...selection.record,...manual}})}
function loadLogForm(){const selection=executionSelection($('logWorkout').value);$('objectiveExecution').innerHTML=objectiveExecutionHtml(selection);Object.entries(MANUAL_LOG_FIELDS).forEach(([el,key])=>{$(el).value=selection.record[key]||'';$(el).oninput=previewAdaptiveAssessment});previewAdaptiveAssessment();}
function saveLogForm(){const selection=executionSelection($('logWorkout').value);const manual=Object.fromEntries(Object.entries(MANUAL_LOG_FIELDS).map(([el,key])=>[key,$(el).value]));if(selection.kind==='activity'){standaloneActivities[selection.id]={...selection.record,...manual,userUpdated:new Date().toISOString()};saveStandaloneActivities();renderAll();toast('Ocena zapisana ✅')}else{logs[selection.id]={...selection.record,...manual,userUpdated:new Date().toISOString()};saveLogs()}}
function deleteLogForm(){const selection=executionSelection($('logWorkout').value);const next={...selection.record};Object.values(MANUAL_LOG_FIELDS).forEach(key=>delete next[key]);delete next.userUpdated;if(selection.kind==='activity'){standaloneActivities[selection.id]=next;saveStandaloneActivities();renderAll();toast('Ocena wyczyszczona')}else{if(next.autoSource||next.parts)logs[selection.id]=next;else delete logs[selection.id];saveLogs()}loadLogForm();}
function standaloneRow(activity){const date=activity.date?new Date(activity.date+'T12:00:00'):new Date();return `<div class="workout-row" onclick="prefillStandalone('${esc(activity.id)}')"><div class="datebox">${fmtDate(date)}<small>Intervals.icu</small></div><div><h4>${esc(activity.name||'Aktywność')}</h4><p>${esc(activity.sport||'Other')} • ${esc(activity.time||0)} min • ${esc(activity.km||0)} km • load ${esc(activity.load||0)}</p><div class="tagline"><span class="pill ${activity.status==='Poza planem'?'':'warn'}">${esc(activity.status||'Poza planem')}</span><span class="pill">Intervals auto</span></div></div><button class="btn" onclick="event.stopPropagation();prefillStandalone('${esc(activity.id)}')">Szczegóły</button></div>`}
function renderRecentLogs(){const planned=Object.keys(logs).map(id=>items.find(x=>x.id===id)).filter(Boolean).map(item=>({kind:'plan',date:item.date,value:item})); const external=Object.values(standaloneActivities).map(item=>({kind:'external',date:new Date((item.date||'1970-01-01')+'T12:00:00'),value:item})); const arr=[...planned,...external].sort((a,b)=>b.date-a.date).slice(0,12); const el=$('recentLogs'); if(el) el.innerHTML=arr.map(row=>row.kind==='plan'?workoutRow(row.value):standaloneRow(row.value)).join('')||'<div class="empty">Jeszcze brak wpisów.</div>'}
function prefillLog(id){showView('log'); setTimeout(()=>{$('logWorkout').value=id; loadLogForm(); window.scrollTo({top:0,behavior:'smooth'})},0)}
function prefillStandalone(id){showView('log');setTimeout(()=>{$('logWorkout').value='activity:'+id;loadLogForm();window.scrollTo({top:0,behavior:'smooth'})},0)}
function renderCoach(){const rd=readiness(); const shoeRows=shoeStats(); const next=findTodayPlan(); $('view-coach').innerHTML=`<div class="grid cols-3">${metric('Readiness',rd.score===null?'—':rd.score+'/100',rd.label||'brak danych',rd.class)}${metric('Ból ≥3 / 14 dni',rd.pain3,'sygnały przeciążenia',rd.pain3>2?'bad':'')}${metric('Mental 7 dni',rd.mental?rd.mental.toFixed(1):'—','głowa / motywacja')}</div>${intervalsCoachPanel()}<div class="section-title"><div><h3>Automatyczny Plan B</h3><p>Dla najbliższej jednostki</p></div></div><div class="card"><div class="detail-grid"><div class="detail-item"><b>Plan</b><p>${esc(next?.discipline)} — ${esc(next?.description)}</p></div><div class="detail-item"><b>Plan B</b><p>${esc(planBFor(next,rd))}</p></div></div></div><div class="section-title"><div><h3>Kalkulator paliwa</h3><p>Dla long runów, zakładek i startów</p></div></div><div class="card"><div class="form-grid"><div><label>Czas treningu (min)</label><input class="input" id="fuelMin" type="number" value="180"></div><div><label>Węgle g/h</label><input class="input" id="fuelCarb" type="number" value="70"></div><div><label>Żel g węgli</label><input class="input" id="fuelGel" type="number" value="25"></div><div><label>Płyn ml/h</label><input class="input" id="fuelFluid" type="number" value="600"></div></div><div id="fuelResult" style="margin-top:14px"></div></div><div class="section-title"><div><h3>Buty / sprzęt</h3><p>Liczone z Twoich wpisów dystansu i pola Buty/sprzęt</p></div></div><div class="card">${shoeRows.length?`<table class="table"><thead><tr><th>Sprzęt</th><th>Km</th><th>Status</th></tr></thead><tbody>${shoeRows.map(r=>`<tr><td>${esc(r.name)}</td><td>${r.km.toFixed(1)}</td><td>${r.km>650?'Wymiana / ostrożnie':r.km>450?'Obserwuj':'OK'}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Wpisz buty/sprzęt i dystans po biegach, a tracker zacznie liczyć przebieg.</div>'}</div><div class="section-title"><div><h3>Predykcja startów</h3><p>Orientacyjnie — na podstawie wpisanych testów</p></div></div><div class="grid cols-2"><div class="card"><h3>Oslo Marathon</h3><p style="color:var(--muted)">${racePredictor('oslo')}</p></div><div class="card"><h3>Ironman 70.3 Poznań</h3><p style="color:var(--muted)">${racePredictor('im')}</p></div></div>`; ['fuelMin','fuelCarb','fuelGel','fuelFluid'].forEach(id=>setTimeout(()=>$(id).oninput=calcFuel)); calcFuel();}
function calcFuel(){const min=num($('fuelMin')?.value), carb=num($('fuelCarb')?.value), gel=num($('fuelGel')?.value)||25, fluid=num($('fuelFluid')?.value); if(!$('fuelResult')) return; const hours=min/60, total=hours*carb, gels=Math.ceil(total/gel), fl=hours*fluid; $('fuelResult').innerHTML=`<div class="grid cols-4">${metric('Węgle razem',Math.round(total)+' g',`${carb} g/h`)}${metric('Żele',gels,`${gel} g/żel`)}${metric('Płyn',Math.round(fl)+' ml',`${fluid} ml/h`)}${metric('Harmonogram',min?`co ${Math.max(20,Math.round(min/gels))} min`:'—','orientacyjnie')}</div>`}
function shoeStats(){const map={}; Object.entries(logs).forEach(([id,l])=>{if(!l.shoes)return; const km=num(l.km); if(!km)return; l.shoes.split(/[,+;/]/).map(s=>s.trim()).filter(Boolean).forEach(s=>map[s]=(map[s]||0)+km)}); return Object.entries(map).map(([name,km])=>({name,km})).sort((a,b)=>b.km-a.km)}
function racePredictor(kind){const arr=Object.keys(logs).map(id=>merged(items.find(x=>x.id===id)||{})).filter(x=>x.id); if(!arr.length)return 'Brak danych. Uzupełnij testy i jednostki kluczowe.'; if(kind==='oslo'){const hm=arr.find(x=>/półmaraton|21,1|21.1/i.test(x.description||'')); const ten=arr.find(x=>/10 km|10km/i.test(x.description||'')); return hm?'Masz wpisany test półmaratoński — użyj jego wyniku/RPE do kalibracji tempa 4:58/km.':'Po teście 10 km i HM aplikacja pokaże bardziej sensowną predykcję. Na razie trzymaj strategię 5:00→4:58/km.'} return 'Dla 70.3 predykcja będzie sensowna po wpisaniu symulacji: open water + rower + T2 oraz treningu 1900 m non-stop.'}

function disciplineType(it){const t=((it.discipline||'')+' '+(it.description||'')).toLowerCase(); if(/wolne|rest/.test(t)) return 'note'; if(/tacx|rower|bike|ftp|z2|z1/.test(t)) return 'ride'; if(/basen|pływ|plyw|open water|kraul|css/.test(t)) return 'swim'; if(/sił|sil|prehab|mobil/.test(t)) return 'strength'; if(/bieg|run|long|maraton|rytmy|interwał|interwal/.test(t)) return 'run'; return 'workout'}
function icsEscape(s){return String(s??'').replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;')}
function ymd(dateISO){return String(dateISO).replace(/-/g,'')}
function foldLine(line){let out=''; while(line.length>73){out+=line.slice(0,73)+'\r\n '; line=line.slice(73)} return out+line}
function addIcsLine(lines,line){lines.push(foldLine(line))}
function workoutBuilderText(it){const type=disciplineType(it); const d=(it.description||'').toLowerCase(); const minutes=num(it.plannedMinutes)||60; if(type==='run'){
  if(/rytmy/.test(d)) return '10m easy warmup\n6x 20s fast relaxed, 90s easy\n10m easy cooldown';
  let m=d.match(/(\d+)\s*[x×]\s*(\d+)\s*km/); if(m) return `15m easy warmup\n${m[1]}x ${m[2]}km hard controlled, 2m easy\n10m easy cooldown`;
  m=d.match(/(\d+)\s*[x×]\s*(\d+)\s*m/); if(m) return `15m easy warmup\n${m[1]}x ${m[2]}m hard controlled, 90s easy\n10m easy cooldown`;
  if(/test|start|półmaraton|polmaraton|21/.test(d)) return '15m easy warmup\nRace/test effort as planned\n10m easy cooldown';
  return `${Math.max(30,minutes)}m easy Z2`;
 }
 if(type==='ride'){
  if(/ftp|test/.test(d)) return '20m warmup\n20m FTP test\n10m cooldown';
  if(/sweet spot|race pace/.test(d)) return `10m Z1 warmup\n${Math.max(30,minutes-20)}m Z2 with planned quality blocks\n10m cooldown`;
  return `${Math.max(30,minutes)}m Z1-Z2`;
 }
 if(type==='swim'){
  if(/1900/.test(d)) return '1900m continuous swim rehearsal';
  if(/css/.test(d)) return 'Warmup\nCSS intervals as planned\nCooldown';
  return 'Easy technique swim as planned';
 }
 if(type==='strength') return 'Strength/prehab session as described in notes';
 return it.description||'Workout as planned';
}
function icsDescription(it){return ['PLAN Z COACH CENTER',`Typ: ${disciplineType(it)}`,`Faza: ${it.Phase||''}`,`Tydzień: ${it.week||''}`,`Intensywność: ${it.intensity||''}`,`Cel: ${it.goal||''}`,'',`Opis: ${it.description||''}`,'',`Plan B: ${it.modification||''}`,'',`Fueling: ${it.breakfast||''} / ${it.dinner||''}`,'','INTERVALS WORKOUT BUILDER:',workoutBuilderText(it)].join('\n')}

function buildStructuredICS(includeNotes=false){const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Oslo Poznan Coach Center Structured//PL','CALSCALE:GREGORIAN','METHOD:PUBLISH','X-WR-CALNAME:Oslo → Poznań Coach Center Structured Garmin']; const now=new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,''); (structuredWorkouts.length?structuredWorkouts:items.map(it=>({id:'fallback-'+it.id,dateISO:it.dateISO,time:'08:00',title:it.discipline,type:disciplineType(it),category:disciplineType(it)==='note'?'NOTE':'WORKOUT',description:icsDescription(it)}))).forEach(ev=>{if(ev.category==='NOTE'&&!includeNotes)return; const start=new Date(ev.dateISO+'T'+(ev.time||'08:00')+':00'); const end=new Date(start); end.setMinutes(end.getMinutes()+garminDuration(ev)); addIcsLine(lines,'BEGIN:VEVENT'); addIcsLine(lines,'UID:'+icsEscape(ev.id+'@coach-center.local')); addIcsLine(lines,'DTSTAMP:'+now); addIcsLine(lines,'DTSTART;TZID=Europe/Oslo:'+dateTimeIcs(start)); addIcsLine(lines,'DTEND;TZID=Europe/Oslo:'+dateTimeIcs(end)); addIcsLine(lines,'SUMMARY:'+icsEscape(ev.title||'Trening')); addIcsLine(lines,'CATEGORIES:'+icsEscape(ev.type||'Workout')); addIcsLine(lines,'DESCRIPTION:'+icsEscape(ev.description||'')); addIcsLine(lines,'END:VEVENT')}); lines.push('END:VCALENDAR'); return lines.join('\r\n')}
function dateTimeIcs(d){const pad=n=>String(n).padStart(2,'0'); return d.getFullYear()+pad(d.getMonth()+1)+pad(d.getDate())+'T'+pad(d.getHours())+pad(d.getMinutes())+pad(d.getSeconds())}
function garminDuration(ev){if(ev.type==='Run')return 75;if(ev.type==='Ride')return 120;if(ev.type==='Swim')return 45;if(ev.type==='Other')return 45;return 15}
function buildICS(mode='structured'){return mode==='all'?buildStructuredICS(true):buildStructuredICS(false)}
function buildIntervalsPayload(){return (structuredWorkouts.length?structuredWorkouts:[]).map(ev=>{const o={category:ev.category||'WORKOUT',start_date_local:ev.dateISO+'T'+(ev.time||'08:00')+':00',name:ev.title||'Trening',description:ev.description||'',external_id:ev.id}; if(ev.category!=='NOTE') o.type=ev.type||'Workout'; return o})}
function copyText(text){navigator.clipboard?.writeText(text).then(()=>toast('Skopiowane ✅')).catch(()=>toast('Nie udało się skopiować'))}
function renderGarmin(){const counts=(structuredWorkouts.length?structuredWorkouts:[]).reduce((m,ev)=>{const t=ev.type||'NOTE'; m[t]=(m[t]||0)+1; return m},{}); const workoutCount=(structuredWorkouts||[]).filter(x=>x.category==='WORKOUT').length; const noteCount=(structuredWorkouts||[]).filter(x=>x.category==='NOTE').length; const hostUrl=(prefs.hostUrl||''); const apiUrl='https://intervals.icu/api/v1/athlete/0/events/bulk?upsert=true'; const curl=`curl -u API_KEY: -H "Content-Type: application/json" -X POST "${apiUrl}" --data-binary @intervals_payload.json`; $('view-garmin').innerHTML=`
  <div class="section-title"><div><h3>Garmin — szczegółowe treningi na zegarku</h3><p>Ta wersja nie wrzuca tylko opisów. Biegi, rowery, baseny i zakładki są rozpisane jako workout builder text dla Intervals.icu.</p></div><span class="pill good">${workoutCount} structured</span></div>
  <div class="grid cols-4">${metric('Run',counts.Run||0,'osobne treningi biegowe')}${metric('Ride',counts.Ride||0,'rower/Tacx/FTP')}${metric('Swim',counts.Swim||0,'basen/open water')}${metric('Notes',noteCount,'wolne/logistyka')}</div>
  <div class="card"><h3 style="margin-top:0">Najpewniejsza ścieżka</h3><ol class="steps"><li>Intervals.icu → Settings → połącz Garmin Connect.</li><li>Włącz opcję <b>Upload planned workouts</b>.</li><li>Wgraj <b>intervals_payload.json</b> przez API albo użyj <b>plan_intervals.ics</b> jako kalendarza.</li><li>Zsynchronizuj zegarek. Garmin dostaje najbliższe planowane treningi jako structured workouts.</li></ol><div class="button-row"><button class="btn primary" id="dlPayload">Pobierz structured payload JSON</button><button class="btn" id="dlIntervalsIcs">Pobierz structured ICS</button><button class="btn" id="dlGoogleIcs">Pobierz zwykły kalendarz</button></div></div>
  <div class="grid cols-2"><div class="card"><h3 style="margin-top:0">Adres po wrzuceniu na hosting</h3><p style="color:var(--muted)">Dla Intervals.icu jako external calendar użyj tego URL.</p><input class="input" id="hostUrl" placeholder="np. https://twoj-plan.netlify.app" value="${esc(hostUrl)}"><div class="detail-item" style="margin-top:12px"><b>URL structured ICS</b><p><code id="icsUrl">${esc(hostUrl?hostUrl.replace(/\/$/,'')+'/garmin/plan_intervals.ics':'Najpierw wpisz URL hostingu')}</code></p></div><button class="btn" id="copyIcsUrl">Kopiuj URL</button></div>
  <div class="card"><h3 style="margin-top:0">API Intervals.icu</h3><p style="color:var(--muted)">Najbardziej szczegółowa opcja. Payload ma pole <code>description</code> z native workout text: kroki, powtórzenia, tempo/power/cadence.</p><div class="button-row"><button class="btn primary" id="dlPayload2">Pobierz intervals_payload.json</button><button class="btn" id="copyCurl">Kopiuj curl</button></div></div></div>
  <div class="card"><h3 style="margin-top:0">Jak są rozbite treningi?</h3><table class="table"><tbody><tr><td><b>Rower długi + T2</b></td><td>Dwa treningi tego samego dnia: Ride + Run T2, żeby Garmin miał właściwy sport.</td></tr><tr><td><b>Bieg + Basen</b></td><td>Dwa treningi: Run rano + Swim wieczorem.</td></tr><tr><td><b>Interwały/MP/race pace</b></td><td>Rozgrzewka → bloki → przerwy → schłodzenie.</td></tr><tr><td><b>Basen</b></td><td>Rozgrzewka, drills, main set, rest, cooldown.</td></tr></tbody></table></div>
  <div class="card"><h3 style="margin-top:0">Podgląd pierwszego structured workout</h3><pre style="white-space:pre-wrap;color:var(--muted);line-height:1.45">${esc((structuredWorkouts.find(x=>x.category==='WORKOUT')||{}).description||'')}</pre></div>`;
  $('dlIntervalsIcs').onclick=()=>downloadText('plan_intervals.ics',buildICS('structured'),'text/calendar');
  $('dlGoogleIcs').onclick=()=>downloadText('plan_google.ics',buildICS('all'),'text/calendar');
  $('dlPayload').onclick=()=>downloadText('intervals_payload.json',JSON.stringify(buildIntervalsPayload(),null,2),'application/json');
  $('dlPayload2').onclick=()=>downloadText('intervals_payload.json',JSON.stringify(buildIntervalsPayload(),null,2),'application/json');
  $('copyCurl').onclick=()=>copyText(curl);
  $('copyIcsUrl').onclick=()=>copyText(($('icsUrl')?.textContent||''));
  $('hostUrl').oninput=()=>{prefs.hostUrl=$('hostUrl').value.trim(); savePrefs(); $('icsUrl').textContent=prefs.hostUrl?prefs.hostUrl.replace(/\/$/,'')+'/garmin/plan_intervals.ics':'Najpierw wpisz URL hostingu'};
}

function renderBackup(){ $('view-backup').innerHTML=`<div class="grid cols-2"><div class="card"><h3>Eksport danych</h3><p style="color:var(--muted)">Pobierz plik JSON i przenieś wpisy na telefon/tablet albo zachowaj backup.</p><button class="btn primary" id="exportBtn">Pobierz backup JSON</button></div><div class="card"><h3>Import danych</h3><p style="color:var(--muted)">Wczytaj wcześniej zapisany backup.</p><input class="input" type="file" id="importFile" accept="application/json"></div></div><div class="section-title"><div><h3>Jak używać na telefonie/tablecie?</h3></div></div><div class="card"><p style="line-height:1.65;color:var(--muted)">Najlepiej wrzucić ten folder na Netlify, GitHub Pages albo własny hosting. Wtedy otwierasz adres w Safari/Chrome i dodajesz do ekranu głównego. Aplikacja jest responsywna i działa jak PWA. Przy otwieraniu samego pliku lokalnie część funkcji offline może być ograniczona przez przeglądarkę.</p></div>`; $('exportBtn').onclick=exportBackup; $('importFile').onchange=importBackup;}
function exportBackup(){const blob=new Blob([JSON.stringify({version:2,created:new Date().toISOString(),logs},null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='coach-center-backup.json'; a.click();}
function importBackup(e){const f=e.target.files[0]; if(!f)return; const r=new FileReader(); r.onload=()=>{try{const data=JSON.parse(r.result); logs=data.logs||data; saveLogs(); toast('Backup wczytany ✅')}catch(err){toast('Nie udało się wczytać JSON')}}; r.readAsText(f)}
function openWorkout(id){const it=items.find(x=>x.id===id); if(!it)return; $('modalTitle').textContent=it.discipline; $('modalSub').textContent=`${fmtDate(it.date)} • ${it['Dzień']||''} • ${it.week}`; const l=getLog(id); const selection={kind:'plan',id,record:l,item:it}; $('modalBody').innerHTML=`${workoutFull(it)}<div class="section-title"><div><h3>Szczegóły wykonania</h3></div></div>${l.updated||l.autoSource?objectiveExecutionHtml(selection):'<div class="empty">Brak dopasowanej aktywności z Intervals.icu.</div>'}${adaptiveAssessmentHtml(selection)}${l.rpe||l.pain||l.sleep||l.mental||l.fuel||l.shoes||l.notes?`<div class="section-title"><div><h3>Moja ocena i notatki</h3></div></div><div class="detail-grid"><div class="detail-item"><b>RPE / ból / sen</b><p>RPE ${esc(l.rpe||'—')} • ból ${esc(l.pain||'—')} • sen ${esc(l.sleep||'—')} h</p></div><div class="detail-item"><b>Mental / sprzęt</b><p>${esc(l.mental||'—')} • ${esc(l.shoes||'—')}</p></div><div class="detail-item"><b>Paliwo</b><p>${esc(l.fuel||'—')}</p></div><div class="detail-item"><b>Prywatna notatka</b><p>${esc(l.notes||'—')}</p></div></div>`:''}<div style="margin-top:16px"><button class="btn primary" onclick="closeModal();prefillLog('${id}')">Dodaj RPE / notatkę</button></div>`; $('detailModal').classList.add('active')}
function closeModal(){$('detailModal').classList.remove('active')}
function toast(msg){const t=$('toast'); t.textContent=msg; t.classList.add('show'); setTimeout(()=>t.classList.remove('show'),2500)}
$('themeBtn').onclick=()=>{document.body.classList.toggle('light'); prefs.light=document.body.classList.contains('light'); savePrefs()}; if(prefs.light) document.body.classList.add('light');
if('serviceWorker' in navigator && location.protocol.startsWith('http')){navigator.serviceWorker.register('sw.js').catch(()=>{})}
autoFillLogsFromIntervals(intervalsData);renderAll();showView('dashboard');
function canAutoSyncIntervals(){return location.protocol.startsWith('http')&&!['localhost','127.0.0.1','::1'].includes(location.hostname)}
if(canAutoSyncIntervals()){setTimeout(()=>syncIntervals(false),1200)}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState!=='visible')return;autoFillLogsFromIntervals(intervalsData);renderAll();if(canAutoSyncIntervals())syncIntervals(false)});
